# Generated by Django 3.0.5 on 2020-05-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hui',
        ),
        migrations.AddField(
            model_name='user',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='blank', max_length=30),
        ),
    ]
